#define SCREEN_WIDTH 1920 / 2
#define SCREEN_HEIGHT 1080 / 2
#define SCALE_X 1
#define SCALE_Y 1

#define GRAVITY 0.1f
#define TERMINAL_VELOCITY 30.0f

#define PLAYER_WIDTH 20
#define PLAYER_HEIGHT 20
#define BOUNCEREDUCTION 1.75f

#define PIPE_WIDTH 60
#define PIPE_HEIGHT ((SCREEN_HEIGHT / 2) - (SCREEN_HEIGHT / 6))

#define GROUND_HEIGHT (SCREEN_HEIGHT - 30)